### ISSUE TITLE
WASI.fork()

### ISSUE THREAD

**Issue by npmccallum** [CraneStation/wasmtime#66]
Please move WASI to a separate repository. I'm interested in being a contributor to WASI, but not necessarily to wasmtime. It would be good to discuss the standard independently from the implementation.

**Comment by sunfishcode** [comment]
I have an agenda item in [the next WebAssembly CG meeting](https://github.com/WebAssembly/meetings/blob/master/2019/CG-04-02.md#agenda-items) to propose a CG Subgroup for the next steps of WASI's evolution and eventual standardization. If this is accepted, then we'll set up a dedicated repository for WASI within the [WebAssembly organization](https://github.com/WebAssembly). If not, we'll look into other options.

Until then, I'd prefer not to create another temporary home. I created a `WASI` issue label in this repository so that we can mark issues and PRs pertaining to WASI, which hopefully sufficies until the real home is ready.

**Comment by sunfishcode** [comment]
[Here's a link](https://github.com/CraneStation/wasmtime/labels/WASI) to quickly show all WASI-specific issues.

**Comment by sunfishcode** [comment]
The CG subgroup is now approved. The dedicated github repo is [here](https://github.com/WebAssembly/WASI/). We'll be migrating content over soon, but for now the issue tracker is at least open.
