### ISSUE TITLE
WASI: remove __wasi_proc_raise()

### ISSUE THREAD

**Issue by npmccallum** [CraneStation/wasmtime#68]
Please remove `__wasi_proc_raise()` from WASI core. If signals are going to be supported, they need to be in a module. Some implementations may choose not to support signals at all.

**Comment by sunfishcode** [comment]
Yeah, `__wasi_proc_raise` in its current form is effectively just a variant of `__wasi_proc_exit` which produces an exit status indicating that the process was killed with a signal rather than exiting normally. So it's obscure, with the only question being whether it's too obscure to be worth including.

If proper signal-handling is ever to be supported, it will depend on new features being added to the core WebAssembly spec. That may happen some day, but on the WASI side there's nothing to do until then.

**Comment by sunfishcode** [comment]
Continuing the discussion at https://github.com/WebAssembly/WASI/issues/7.
