### ISSUE TITLE
WASI should be a set of sandbox oriented APIs

### ISSUE THREAD

**Issue by J-F-Liu** [CraneStation/wasmtime#95]
It should be safe to run third party code like what a web browser has already done, but without the complexity of Web API. Consider what inputs and outputs are allowed for a sandbox:
- console read and write abilities to create TUI applications
- pixel based canvas apis to create GUI applications
- vector based SVG display to create scalable GUI
- webgl like apis to create 3D applications
- keyboard, mouse, touch screen inputs
- local storage and network access apis

This is much like creating a game console rather than a web browser, leave high level abstractions to application frameworks.

**Comment by sunfishcode** [comment]
Indeed, those are areas we're hoping WASI will grow to address (in a modular way)!

**Comment by J-F-Liu** [comment]
But file system operations are unsafe, should push off __wasi_fd_**** APIs as far as possible.

**Comment by sunfishcode** [comment]
WASI's capability-based security design ensures that applications can't access the filesystem by default. They can only do so through capabilities provided to them. In this way, environments can allow limited access, or no access, as they see fit.

And, the plan is to make WASI modular, so that environments that don't have a filesystem don't need to present those APIs.
